version: 0.0
os: linux
files:
  - source: target/
    destination: /usr/share/nginx/html
hooks:
#  BeforeInstall:
    #- location: 
    #- location: 
#  AfterInstall:
#  This is to be handled by configuration management since we are provisioning the nginx webserver
    #- location: scripts/install_dependencies
    #  timeout: 300
    #  runas: root
    #  runas: geostoreuser
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
      #runas: root
      runas: geostoreuser
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3600
      #runas: root
      runas: geostoreuser
  
