version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
#  BeforeInstall:
    #- location: 
    #- location: 
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3600
      runas: root
  
