version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
#hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: Scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_server
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: Scripts/stop_server
      timeout: 3600
      runas: root
  
