version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Launch geostore in a servlet container
      - cd src/web/app
      - mvn jetty:run
  post_build:
    commands:
      - echo Build completed on `date`
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR/src/web/app
artifacts:
  files:
    - web/app/**/*
    - appspec.yml
  #name: $AWS_REGION-$(date +%Y-%m-%d)
